export const EXPERTISE_OPTIONS = [
    "Apologetics",
    "Children",
    "Christian living",
    "Culture",
    "Education",
    "Family",
    "Grief & bereavement",
    "Health & Wellbeing",
    "History",
    "Justice",
    "Leadership",
    "Marriage",
    "Mental health",
    "Music",
    "Politics",
    "Prayer",
    "Prison",
    "Prophecy",
    "Renewal",
    "Science",
    "Sexuality & gender",
    "Social action",
    "Social care",
    "Sport",
    "Supernatural",
    "Technology",
    "Testimony",
    "Theology",
    "UK Church",
    "US Church",
    "Work",
    "Young adults"
];
